apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: deployment-api
  namespace: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-api
  template:
    metadata:
      labels:
        app: deployment-api
    spec:
      containers:
      - name: deployment-api
        image: fiaptechchallenge04acr.azurecr.io/tech-challenge-04-order-image
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"  
          requests:
            cpu: "500m"
            memory: "512Mi"  
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_SECRET
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: USER_SERVICE_URL
        - name: CATALOG_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: CATALOG_SERVICE_URL
        - name: STATUS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: STATUS_SERVICE_URL
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: PAYMENT_SERVICE_URL
        
        # Probes
        # startupProbe:
        #   httpGet:
        #     path: /health-start
        #     port: 3333
        #   failureThreshold: 30 
        #   periodSeconds: 10    
        #   initialDelaySeconds: 180 # becausa of the memory config 
        # readinessProbe:
        #   httpGet:
        #     path: /health-read
        #     port: 3333
        #   initialDelaySeconds: 180 # becausa of the memory config
        #   periodSeconds: 10
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     path: /health-live
        #     port: 3333
        #   initialDelaySeconds: 180 # becausa of the memory config
        #   periodSeconds: 10
        #   failureThreshold: 5 
